export const movieList=[
    {id:1,titre:"The message", slach:"Themessage", description:"Ce filme présente la vie du prophète Mohamed (benédiction et salu de dieu)", posterURL:"https://static.cinemagia.ro/img/resize/db/movie/03/06/51/the-message-937286l-600x0-w-c1d8a6be.jpg", rating:5, 
    srce:"https://www.youtube.com/embed/gRo7rjAiAw8", title:"The Message 4K Restoration English Version |2018| Official HD Trailer" },
    {id:2,titre:"My name is khan", slach:"Mynameiskhan", description:"La soufrance des musulmans dans USA aprés le 11 septembre", posterURL:"https://amc-theatres-res.cloudinary.com/v1584617884/amc-cdn/production/2/movies/17100/17061/Poster/p_800x1200_AMC_MyNameIsKhan_03172020.jpg", rating:4.5,
     srce:"https://www.youtube.com/embed/nqxgYT3TYzY", title:"My Name is KHAN - MNIK (Official International Trailer HD)"},
    {id:3,titre:"Rapunzel", slach:"Rapunzel", description:"l'hystoire de la belle fille Rapunzel avec la sorcière et le prince charmant", posterURL:"https://pre00.deviantart.net/54d7/th/pre/f/2012/257/b/e/rapunzel_poster_by_1tangledfanref-d5eo2qj.jpg", rating:2.5, 
    srce:"https://www.youtube.com/embed/2f516ZLyC6U", title:"Tangled: Trailer 1"},
    {id:4,titre:"Frozen", slach:"Frozen", description:"l'hystoire des soeures, l'une a un pouvoir magique", posterURL:"https://picfiles.alphacoders.com/147/147202.jpg", rating:3,
     srce:"https://www.youtube.com/embed/FLzfXQSPBOg", title:"Frozen Official Elsa Trailer (2013) - Disney Animated Movie HD"},
    {id:5,titre:"The lord of the rings", slach:"Thelordoftherings", description:"l'hystoire des secrets des bagues magiques et leurs pouvoirs", posterURL:"https://th.bing.com/th/id/OIP.UvXqLfOnpCt8ZEeDelfyUgHaK9?pid=ImgDet&rs=1", rating:5, 
    srce:"https://www.youtube.com/embed/x8UAUAuKNcU", title:"The Lord of the Rings: The Rings of Power - Official Trailer | Prime Video"},
    {id:6,titre:"Herry Potter", slach:"HerryPotter", description:"l'hystoire de la magie avec Herry potter et ses amis", posterURL:"https://th.bing.com/th/id/R.b0bbb5b50e2e397c7860ca6f67934db1?rik=f5%2bJkedtstzExQ&riu=http%3a%2f%2fwww.collider.com%2fwp-content%2fuploads%2fharry_potter_and_the_deathly_hallows_movie_poster_daniel_radcliffe_hi-res_01.jpg&ehk=xDUYliAhviguLBq3nxRFdJxQsaOeITN8qrGdn2GROsg%3d&risl=&pid=ImgRaw&r=0", rating:4.5,
     srce:"https://www.youtube.com/embed/fFGS4zZWGoA", title:"Harry Potter 20th Anniversary: Return to Hogwarts | Official Trailer | HBO Max" },
    {id:7,titre:"Pokemon Detective Pikachu", slach:"PokemonDetectivePikachu", description:"un pokémon a décidé de découvrir la vérité", posterURL:"https://buzz.tt/media/posters/2405/posters_1_1500.jpg", rating:4.5, 
    srce:"https://www.youtube.com/embed/1roy4o4tqQM", title:"POKÉMON Detective Pikachu - Official Trailer #1"},
    {id:8,titre:"Detective Conan", slach:"DetectiveConan", description:"le petit détective cherche le coupable pour sauver le bateau", posterURL:"https://th.bing.com/th/id/R.d0dec41f2b92ffff32a63e4757a7777d?rik=kz8ThX92VkeJVg&riu=http%3a%2f%2fstatic.minitokyo.net%2fdownloads%2f37%2f27%2f273887.jpg&ehk=IjxMfxg7dvl%2f13s5MEf5XLAWb1nwMFNBLScXrlfQ%2bgQ%3d&risl=&pid=ImgRaw&r=0", rating:4, 
    srce:"https://www.youtube.com/embed/5DcWtjrYcFI", title:"Detective Conan: The Bride of Halloween - Movie Trailer 2 (English Subtitles)"},
    {id:9,titre:"Dachra", slach:"Dachra", description:"l'engoisse d'une village mistérieuse avec la magie noire", posterURL:"https://th.bing.com/th/id/R.1ae09ca241670094536954ecd2c4ccaa?rik=8pIczPwD%2f7eqNA&riu=http%3a%2f%2fwww.nerdly.co.uk%2fwp-content%2fuploads%2f2019%2f08%2fdachra-poster.jpg&ehk=6w2kibdB7Wjfg9q%2fO9IXxbEFvqHoQjJMk6cF4kVxz68%3d&risl=&pid=ImgRaw&r=0", rating:"4.5", 
    srce:"https://www.youtube.com/embed/xSAUJihktLk", title:"Dachra Trailer | ARROW"}]
